###
POST http://localhost:8080/message/history
Content-Type: application/json

{
  "userIdFrom" : "u2",
  "userIdTo" :"u1",
  "pageIndex":  0,
  "pageSize": 10
}

###
POST http://localhost:8080/message/history/user
Content-Type: application/json

{
  "userId": "u1",
  "pageIndex": 0,
  "pageSize": 20
}