###
POST http://localhost:10000/message/history
Content-Type: application/json

{
  "userIdFrom" : "u2",
  "userIdTo" :"u1",
  "pageIndex":  1,
  "pageSize": 1000
}

###
POST http://localhost:10000/message/history/user
Content-Type: application/json

{
  "userId": "9388cb37-f57f-11ed-9dc2-0242ac130003",
  "pageIndex": 0,
  "pageSize": 20
}